language: java

before_install: (cd parent && exec mvn install)

notifications:
  irc: "irc.oftc.net#mammon"
  template:
    - "%{branch}/%{commit} (#%{build_number} by %{author}): %{mesage} %{build_url}"

